
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int keywords_null = 34;
  public static final int keywords_class = 29;
  public static final int keywords_Read = 43;
  public static final int keywords_interface = 33;
  public static final int keywords_dtoi = 50;
  public static final int plus = 2;
  public static final int mod = 7;
  public static final int double_const = 28;
  public static final int minus = 4;
  public static final int keywords_else = 35;
  public static final int gt = 9;
  public static final int nequal = 13;
  public static final int keywords_itod = 49;
  public static final int keywords_if = 32;
  public static final int keywords_itob = 51;
  public static final int keywords_public = 59;
  public static final int type_double = 54;
  public static final int type_int = 53;
  public static final int keywords_btoi = 52;
  public static final int keywords_break = 39;
  public static final int identifier = 61;
  public static final int open_parenthese = 23;
  public static final int type_bool = 55;
  public static final int ge = 11;
  public static final int open_brace = 21;
  public static final int keywords_extends = 30;
  public static final int keywords_Print = 41;
  public static final int equal = 12;
  public static final int keywords_while = 36;
  public static final int keywords_for = 37;
  public static final int divide = 6;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int keywords_implements = 31;
  public static final int lt = 8;
  public static final int keywords_protected = 60;
  public static final int type_void = 57;
  public static final int key_words_NewArray = 48;
  public static final int or = 15;
  public static final int colon = 17;
  public static final int open_bracket = 19;
  public static final int bool_const = 27;
  public static final int keywords_Integer = 44;
  public static final int close_brace = 22;
  public static final int keywords_continue = 40;
  public static final int le = 10;
  public static final int exclamation = 16;
  public static final int semiColon = 18;
  public static final int keywords_private = 58;
  public static final int mult = 3;
  public static final int keywords_new = 47;
  public static final int and = 14;
  public static final int keywords_ReadInteger = 45;
  public static final int close_parenthese = 24;
  public static final int assign = 5;
  public static final int keywords_this = 42;
  public static final int keywords_ReadLine = 46;
  public static final int type_string = 56;
  public static final int keywords_return = 38;
  public static final int numbers = 26;
  public static final int dot = 25;
  public static final int close_bracket = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "plus",
  "mult",
  "minus",
  "assign",
  "divide",
  "mod",
  "lt",
  "gt",
  "le",
  "ge",
  "equal",
  "nequal",
  "and",
  "or",
  "exclamation",
  "colon",
  "semiColon",
  "open_bracket",
  "close_bracket",
  "open_brace",
  "close_brace",
  "open_parenthese",
  "close_parenthese",
  "dot",
  "numbers",
  "bool_const",
  "double_const",
  "keywords_class",
  "keywords_extends",
  "keywords_implements",
  "keywords_if",
  "keywords_interface",
  "keywords_null",
  "keywords_else",
  "keywords_while",
  "keywords_for",
  "keywords_return",
  "keywords_break",
  "keywords_continue",
  "keywords_Print",
  "keywords_this",
  "keywords_Read",
  "keywords_Integer",
  "keywords_ReadInteger",
  "keywords_ReadLine",
  "keywords_new",
  "key_words_NewArray",
  "keywords_itod",
  "keywords_dtoi",
  "keywords_itob",
  "keywords_btoi",
  "type_int",
  "type_double",
  "type_bool",
  "type_string",
  "type_void",
  "keywords_private",
  "keywords_public",
  "keywords_protected",
  "identifier"
  };
}

