
// this enum defines all tokens including keywords and Token Types
enum TokenTypes {
    T_ID,T_INTLITERAL,
    T_DOUBLELITERAL,
    EOF,INT,EOL,
    VOID,DOUBLE, BOOL,T_STRINGLITERAL,
    STRING, CLASS, INTERFACE,
    NULL, THIS, EXTENDS,
    IMPLEMENTS, FOR, WHILE,
    IF, ELSE, RETURN,
    BREAK, CONTINUE, NEW,
    NEWARRAY, PRINT, READ,
    INTEGER, READLINE,
    DTOI, ITOD, BTOI,
    ITOB, PRIVATE, PROTECTED,
    PUBLIC,OPERATORS,COMPARATORS,
    SEPERATORS,LOGICALOPERATORS,T_BOOLEANLITERAL,READINTEGER,ERR

    ;


}